#!/usr/bin/env python
# coding: utf-8

# In[27]:


string1= "and or and with or not go for and not got for with and for go on there" ## Enter the string to be compressed
print('The size of encoded string is:'+str(sys.getsizeof(string1)) +' bytes')
list1= string1.split() #separate individual words in the string


import numpy as np
import sys
dict1={} ## create dictionary to store the word in the list as key and iths freuquency as value

for i in list1:
    count= list1.count(i) #count frequency of occurence of word in the list
    temp= {i:count} 
    dict1.update(temp) # update the dictionary with word and its frequency

a= np.array(dict1)
print(a)

import pandas as pd
df1=pd.DataFrame(dict1.items()) #display the dictionary as dataframe using pandas
df1.columns= ['word', 'frequency']
#Display the dataframe with word and its frequency
print("\nDataframe of word and its corresponding frequency is:\n")
print(df1)

k=0
dict2={} # create one more dictionary to store word and its corresponding index
for key1 in dict1:
    k= k+1
    temp = {key1:k}
    dict2.update(temp)
print("\n The dictionary with word and its corresponding index is:\n")
print(dict2)
list2=[]
##output the index of the word in the list to obtain compressed text
for p in range(len(list1)):
    for j in dict2:
        if j== list1[p]:
            list2.append(dict2[j])
string2 =str(list2)

print("\n The encoded string is:\n")
print(string2)
print('The size of encoded string is:'+str(sys.getsizeof(string2)) +' bytes')



# In[ ]:





# In[ ]:





# In[ ]:





# In[ ]:




